# coding: utf-8
Client.create(name: "JRDM", contact_id: 1)
Client.create(name: "RaseCampagneImmo")
Contact.create(name: "Eric Chatry", client: Client.first)
Contact.create(name: "M. Sometime", client_id: 2)
Contact.create(name: "Mme. Chose", client_id: 2)
Bill.create(title: "Pack complet 1 ans", amount: 5000, due_date: Date.today-15, client_id: 2, emission_date: Date.today-31, paid: true)
Bill.create(title: "Achat nom de domaine", amount: 50, due_date: Date.today-15, client_id: 2, emission_date: Date.today-31, paid: false)
Bill.create(title: "Mise à jour serveur", amount: 200, due_date: Date.today+31, client_id: 2, emission_date: Date.today)
Bill.create(title: "Intervention serveur", amount: 200, due_date: Date.today+14, client_id: 2, emission_date: Date.today)
Bill.create(title: "Intervention serveur", amount: 200, due_date: Date.today-1, client_id: 2, emission_date: Date.today-14, paid: true)
Bill.create(title: "Intervention serveur", amount: 200, due_date: Date.today-1, client_id: 2, emission_date: Date.today-14)
Bill.create(title: "Mise en place d'API", amount: 2000, due_date: Date.today+31, client_id: 2, emission_date: Date.today)
Ticket.create(title: "Pas possible d'éditer la page d'acceuil", bill_id: 1, client_id: 2)
Ticket.create(title: "Vous avez supprimé une page. Elle a été remise en place gratuitement.", bill_id: 1, client_id: 2, ticket_id: 1)
